spring:
  datasource:
    # 配置自带数据库的相对路径
    #url: jdbc:h2:~/.chat2db/db/chat2db_dev;MODE=MYSQL
    #driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://gz-cdb-4dacc8h7.sql.tencentcdb.com:63621/chat2db_dev?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2
  #     settings:
  #       trace: true
  #       web-allow-others: true
# 端口号
server:
  port: 10821

chat2db:
  gateway:
    base-url: http://test.sqlgpt.cn/gateway
    model-base-url: http://test.sqlgpt.cn/gateway